apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
        ports:
          - containerPort: 8080
        env:
          - name: MONGODB_ENABLED
            value: "true"
          - name: MONGODB_URI
            value: mongodb://test:test123@13.212.83.157:27017/test
        imagePullPolicy: Always
        restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007