version: '3.8'

services:
  mongodb:
    image: mongo:4.2.21
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb/local-env/:/docker-entrypoint-initdb.d/

volumes:
  mongo-data:
    driver: local
